2024-05-19 01:53:44 [scrapy.core.engine] ERROR: Scraper close failure
Traceback (most recent call last):
  File "E:\Softwares\Anaconda\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "D:\2024Spring\DLsite-Analysis\MainSite_Crawler\MainSite_CrawlerV2.0\MainSite_Crawler\pipelines.py", line 79, in close_spider
    copy_dict[each['Status']].remove(each['Site'])
ValueError: list.remove(x): x not in list
